server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/event-management?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      jdbc.time_zone: Asia/Ho_Chi_Minh
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
  jackson:
    date-format: dd-MM-yyyy HH:mm:ss
    time-zone: Asia/Ho_Chi_Minh
  application:
    timezone: Asia/Ho_Chi_Minh
  mail:
    host: smtp.gmail.com
    port: 587
    username: "hoanggthanhh9988@gmail.com"
    password: "vsgpwbfodmvcxncz"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
api:
  prefix: api/v1
resource:
  suitableQuantity: 300
  noImageUrl: https://res.cloudinary.com/dcw5wq1ka/image/upload/v1729736990/no-image-found.png
  logoImageUrl: https://upload.wikimedia.org/wikipedia/vi/c/ce/Logo_Tr%C6%B0%E1%BB%9Dng_%C4%90%E1%BA%A1i_h%E1%BB%8Dc_Tr%C3%A0_Vinh.png
cloudinary:
  cloud_name: dcw5wq1ka
  api_key: 228462159873377
  api_secret: VOz0qy1Fh1TwwdqF5ZXjpytRVjY
jwt:
  expiration: 36000 #10hours = 10* 60 * 60
  secretKey: Z7hjrPTXlc9XLzJCO7kyYZWh1DiskWLbplYzgBHIREU=
